//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfASADACore.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wpfASADACore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Factura&lt;/title&gt;
        ///    &lt;style&gt;
        ///        table {
        ///            width: 100%;
        ///            border-collapse: collapse;
        ///        }
        ///        th, td {
        ///            border: 1px solid black;
        ///            padding: 15px;
        ///            text-align: left;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;Factura No: {InvoiceNum}&lt;/h2&gt;
        ///    &lt;p&gt;Fecha: {BillingDate}&lt;/p&gt;
        ///    &lt;h3&gt;Detalles del Cliente&lt;/h3&gt;
        ///    &lt;p&gt;ID del Cliente: {idClient}&lt;/p&gt;
        ///    &lt;p&gt;Nombre del Cliente: {ClientName} { [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string facturaAsada {
            get {
                return ResourceManager.GetString("facturaAsada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Factura&lt;/title&gt;
        ///  &lt;style&gt;
        ///    /* Fuente y tamaño de letra */
        ///    body {
        ///      font-family: Arial, sans-serif;
        ///      font-size: 16px;
        ///    }
        ///
        ///    /* Colores y contraste */
        ///    body {
        ///      background-color: #f5f5f5;
        ///      color: #333;
        ///    }
        ///
        ///    /* Alineación y espaciado */
        ///    table {
        ///      width: 100%;
        ///      border-collapse: collapse;
        ///      margin-bottom: 20px;
        ///    }
        ///
        ///    th, td {
        ///      padding: 10px;
        ///      text-align: left;
        ///    }
        ///
        ///    /* U [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string facturaAsada2 {
            get {
                return ResourceManager.GetString("facturaAsada2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Factura&lt;/title&gt;
        ///  &lt;style&gt;
        ///    body {
        ///      font-family: &apos;Roboto&apos;, sans-serif;
        ///      margin: 0;
        ///      padding: 20px;
        ///      background-color: #f5f5f5;
        ///      color: #333;
        ///    }
        ///
        ///    .invoice-container {
        ///      max-width: 800px;
        ///      margin: 0 auto;
        ///      background-color: white;
        ///      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        ///      padding: 30px;
        ///    }
        ///
        ///    h2, h3 {
        ///      text-align: center;
        ///      margin-bottom: 20px;
        ///    }
        ///
        ///    table {
        ///      wid [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string facturaAsada3 {
            get {
                return ResourceManager.GetString("facturaAsada3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Factura&lt;/title&gt;
        ///  &lt;style&gt;
        ///    body {
        ///      font-family: Arial, sans-serif;
        ///      margin: 0;
        ///      padding: 0;
        ///      background-color: #f4f4f4;
        ///    }
        ///
        ///    .invoice-header, .invoice-footer {
        ///      background-color: #333;
        ///      color: #fff;
        ///      padding: 20px;
        ///      text-align: center;
        ///    }
        ///
        ///    .invoice-header h2 {
        ///      margin: 0;
        ///    }
        ///
        ///    .invoice-content {
        ///      max-width: 800px;
        ///      margin: 20px auto;
        ///      background-color: #fff;
        ///    [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string facturaAsada4 {
            get {
                return ResourceManager.GetString("facturaAsada4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] water_system {
            get {
                object obj = ResourceManager.GetObject("water_system", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
